apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  database_password: {{ .Values.secret.database_password }}
  database_user: {{ .Values.secret.database_user }}
