{{- $highAvailability := gt (int .Values.keycloak.replicas) 1 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "keycloak-chart.fullname" . }}-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "keycloak-chart.name" . }}
    chart: {{ template "keycloak-chart.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.keycloak.service.port }}
      targetPort: http
      protocol: TCP
  {{- if $highAvailability }}
    - name: jgroups
      port: {{ .Values.keycloak.service.jgroupsPort }}
      targetPort: jgroups
      protocol: TCP
  {{- end }}
  selector:
    app: {{ template "keycloak-chart.name" . }}
    release: "{{ .Release.Name }}"
