apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "keycloak-chart.fullname" . }}
  namespace: default
spec:
  gateways:
  - {{ .Values.virtualService.gateway }}
  hosts:
  - {{ .Values.virtualService.host }}
  http:
  - fault:
      abort:
        httpStatus: 403
        percent: 0
    match:
    - uri:
        prefix: /{{ .Values.keycloak.basepath }}/admin/master/console
    route:
    - destination:
        host: {{ template "keycloak-chart.fullname" . }}-http.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: 80
  - fault:
      abort:
        httpStatus: 403
        percent: 0
    match:
    - uri:
        prefix: /{{ .Values.keycloak.basepath }}/realms/master
    route:
    - destination:
        host: {{ template "keycloak-chart.fullname" . }}-http.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /{{ .Values.keycloak.basepath }}
    route:
    - destination:
        host: {{ template "keycloak-chart.fullname" . }}-http.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: 80

