apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: elasticsearch
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    generation: null
    importPolicy: {}
    name: ""
    referencePolicy:
      type: ""
