apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  generation: 1
  name: elasticsearch
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/openshift/elasticsearch
  tags:
  - items:
    - created: "2021-03-31T12:56:46Z"
      dockerImageReference: docker.elastic.co/elasticsearch/elasticsearch@sha256:0e0fd27c4e133399d8c5419141915cbf04966aa808427f21bd316fb7c5bed61f
      generation: 1
      image: sha256:0e0fd27c4e133399d8c5419141915cbf04966aa808427f21bd316fb7c5bed61f
    tag: latest
