apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"image.openshift.io/v1","kind":"ImageStream","metadata":{"annotations":{"openshift.io/image.dockerRepositoryCheck":"2021-04-01T05:40:53Z"},"creationTimestamp":"2021-04-01T05:40:52Z","generation":2,"labels":{"app.kubernetes.io/instance":"easticsearch"},"managedFields":[{"apiVersion":"image.openshift.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:openshift.io/image.dockerRepositoryCheck":{}},"f:labels":{".":{},"f:app.kubernetes.io/instance":{}}},"f:spec":{"f:tags":{".":{},"k:{\"name\":\"latest\"}":{".":{},"f:annotations":{},"f:from":{".":{},"f:kind":{},"f:name":{}},"f:generation":{},"f:importPolicy":{},"f:name":{},"f:referencePolicy":{".":{},"f:type":{}}}}},"f:status":{"f:dockerImageRepository":{},"f:tags":{".":{},"k:{\"tag\":\"latest\"}":{".":{},"f:items":{},"f:tag":{}}}}},"manager":"argocd-application-controller","operation":"Update","time":"2021-04-01T05:40:52Z"}],"name":"elasticsearch","namespace":"openshift","resourceVersion":"4150341","selfLink":"/apis/image.openshift.io/v1/namespaces/openshift/imagestreams/elasticsearch","uid":"4a90fed6-2e57-412a-8ed8-4610ea56a886"},"spec":{"lookupPolicy":{"local":false},"tags":[{"annotations":null,"from":{"kind":"DockerImage","name":"docker.elastic.co/elasticsearch/elasticsearch:6.8.8"},"generation":0,"importPolicy":{},"name":"latest","referencePolicy":{"type":"Source"}}]}}
    openshift.io/image.dockerRepositoryCheck: "2021-04-01T05:46:13Z"
  creationTimestamp: null
  generation: 1
  labels:
    app.kubernetes.io/instance: easticsearch
  managedFields:
  - apiVersion: image.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:openshift.io/image.dockerRepositoryCheck: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
      f:spec:
        f:tags:
          .: {}
          k:{"name":"latest"}:
            .: {}
            f:annotations: {}
            f:from:
              .: {}
              f:kind: {}
              f:name: {}
            f:generation: {}
            f:importPolicy: {}
            f:name: {}
            f:referencePolicy:
              .: {}
              f:type: {}
      f:status:
        f:dockerImageRepository: {}
    manager: argocd-application-controller
    operation: Update
    time: "2021-04-01T05:46:12Z"
  name: elasticsearch
  selfLink: /apis/image.openshift.io/v1/namespaces/openshift/imagestreams/elasticsearch
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
