apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle
  namespace: oracle
spec:
  selector:
    matchLabels:
      app: oracle
  serviceName: "oracle"
  replicas: 1
  template:
    metadata:
      labels:
        app: oracle
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: oracle
        image: image-registry.openshift-image-registry.svc:5000/openshift/oracle-xe-11g
        ports:
        - containerPort: 1521
          name: listener
        volumeMounts:
        - name: oracle
          mountPath: /u01/app/oracle-product
        - name: secondoracle
          mountPath: /u01/app/oracle
  
  volumeClaimTemplates:
  - metadata:
      name: oracle
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-standard"
      resources:
        requests:
          storage: 5Gi
   - metadata:
      name: secondoracle
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-standard"
      resources:
        requests:
          storage: 1Gi         
