apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle
  namespace: oracle
spec:
  selector:
    matchLabels:
      app: oracle
  serviceName: "oracle"
  replicas: 1
  template:
    metadata:
      labels:
        app: oracle
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: oracle
        image: ejlp12/docker-oracle-xe
        ports:
        - containerPort: 1521
          name: listener
        volumeMounts:
        - name: oracle
          mountPath: /tmp/oracle
  volumeClaimTemplates:
  - metadata:
      name: oracle
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-standard"
      resources:
        requests:
          storage: 5Gi      
