apiVersion: v1
kind: Service
metadata:
  name: oracle
  namespace: oracle
  labels:
    app: oracle
spec:
    ports:
    - name: 1521-tcp
      nodePort: 32754
      port: 1521
      protocol: TCP
      targetPort: 1521
    - name: 8080-tcp
      nodePort: 30340
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: oracle
    sessionAffinity: None
    type: LoadBalancer
