apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle
  namespace: oracle
spec:
  selector:
    matchLabels:
      app: oracle
  serviceName: "oracle"
  replicas: 1
  template:
    metadata:
      labels:
        app: oracle
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: oracle
        image: oracleinanutshell/oracle-xe-11g
        ports:
        - containerPort: 1521
          name: listener
  
  volumeClaimTemplates:
  - metadata:
      name: oracle1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-standard"
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: secondoracle
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-standard"
      resources:
        requests:
          storage: 1Gi         
