namespace: cust360
deployment:
  name: auth-audit
  image:
    name: registry-k8s.yesbank.in/auth-service
    tag: latest
  containerPort: 8080
  resources:
    requests:
      cpu: "200m"
      memory: 3Gi
      javaHeap: 2048m
    limits:
      cpu: "500m"
      memory: 3Gi
      javaHeap: 2048m

service:
  name: auth-audit-svc
  type: ClusterIP
  port: 80
  targetPort: 8080
  portName: http


configMap:
  name: auth-audit
  timeZone: Asia/Kolkata
  authServerService: https://sso.genie.yesbank.in
  yblMSRealm: YBL
  msClientId: yes-genie-frontend
  spring_active_profile: prod

  loggingLevelRoot: INFO


virtualService:
  name: auth-service
  uri1: /api/user/login/audit
  host1: cust360.genie.yesbank.in

autoscaler:
  name: auth-audit-as

